apiVersion: v1
kind: Pod
metadata:
  name: nagios-retriever
spec:
  containers:
  - name: nagios-retriever
    image: mmaschenk/nagios-retriever:1.1
    envFrom:
    - secretRef:
        name: passwords
    - configMapRef:
        name: environment